Javascript bank
Quintin-Russell/m2-0621-code-solutions pull request #7
Opened 2021-06-25 02:59 UTC by Quintin-Russell

![image](https://user-images.githubusercontent.com/75178406/123363119-b2319700-d526-11eb-9084-384879f63261.png)

2021-06-25 03:44 UTC, TimelikeClosure requested changes

2021-06-25 03:44 UTC, TimelikeClosure commented on javascript-bank/account.js
> +};
The balance should be calculated in the `getBalance` method, not beforehand.

---

![image](https://user-images.githubusercontent.com/16143771/123365410-16565a00-d52b-11eb-952e-6cefa5060cb1.png)

2021-06-25 03:44 UTC, TimelikeClosure commented on javascript-bank/account.js
> +    this.number -= amt;
The `number` property is a unique account number identifier and should not change for the life of the account.

---

![image](https://user-images.githubusercontent.com/16143771/123365534-4a317f80-d52b-11eb-9b25-dbd832bccb31.png)

2021-06-25 03:44 UTC, TimelikeClosure commented on javascript-bank/bank.js
> +    let acc = new Account(balance, holder);
The first parameter of the `Account` constructor is the account number, not the balance.

---

![image](https://user-images.githubusercontent.com/16143771/123365770-caf07b80-d52b-11eb-8af9-e1f9be98b333.png)

2021-06-25 03:44 UTC, TimelikeClosure commented on javascript-bank/bank.js
> +    acc.balance = balance;
In line with "encapsulation", external code should not directly modify an `Account` instance's properties. It should make use of the `Account`'s methods instead.

2021-06-25 03:44 UTC, TimelikeClosure commented on javascript-bank/bank.js
> +  for (let acc of this.accounts) {
Can you explain how `for ... of` loops work? If so, great! If not, use something more basic.

2021-06-25 03:44 UTC, TimelikeClosure commented on javascript-bank/bank.js
> +    if (acc.nextAccountNumber === number) {
There should not be a `nextAccountNumber` property on `Account`s.

---

![image](https://user-images.githubusercontent.com/16143771/123366308-d85a3580-d52c-11eb-9110-ba34e04f11fc.png)

2021-06-25 03:44 UTC, TimelikeClosure commented on javascript-bank/bank.js
> +    total += acc.balance
There should not be a `balance` property on `Account`s:

---

![image](https://user-images.githubusercontent.com/16143771/123366354-ead46f00-d52c-11eb-8a04-2b271007f638.png)

2021-06-28 22:08 UTC, TimelikeClosure requested changes
@Quintin-Russell A couple of the previous issues weren't fixed.

2021-06-29 01:23 UTC, Quintin-Russell commented
could you please be more specific next time. thank you!

2021-06-29 02:34 UTC, TimelikeClosure approved these changes

2021-06-29 03:03 UTC, merged